config/routes.rb
Rails.application.routes.draw do
  resources :authors, only: [:index, :show] do
    resources :books
  end

  namespace :admin do
    resources :authors
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to [:admin, @author], notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to [:admin, @author], notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to admin_authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :main_genre, :birthdate, :info)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :set_author

  # GET /books
  # GET /books.json
  def index
    @books = author.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = author.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = author.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to [@author, @book], notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: [@author, @book] }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to [@author, @book], notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to author_books_url(@author), notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # because all the book routes are under author, we're pretty much
    # always going to want to get the corresponding author
    def author
      Author.find(params[:author_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_author
      @author = author
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :genre, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/authors/_form.html.erb
<%= form_with(model: [:admin, author], local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :main_genre %>
    <%= form.text_field :main_genre, id: :author_main_genre %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, id: :author_birthdate %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info, id: :author_info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', [:admin, @author] %> |
<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Main genre</th>
      <th>Birthdate</th>
      <th>Info</th>
      <th>Books</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.main_genre %></td>
        <td><%= author.birthdate %></td>
        <td><%= author.info %></td>
        <td><%= link_to 'Books', [author, :books] %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_admin_author_path(author) %></td>
        <td><%= link_to 'Destroy', [:admin, author], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_admin_author_path %>

app/views/admin/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Main genre:</strong>
  <%= @author.main_genre %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @author.birthdate %>
</p>

<p>
  <strong>Info:</strong>
  <%= @author.info %>
</p>

<%= link_to 'Edit', edit_admin_author_path(@author) %> |
<%= link_to 'Back', admin_authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Main genre</th>
      <th>Birthdate</th>
      <th>Info</th>
      <th>Books</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.main_genre %></td>
        <td><%= author.birthdate %></td>
        <td><%= author.info %></td>
        <td><%= link_to 'Books', [author, :books] %></td>
        <td><%= link_to 'Show', author %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Main genre:</strong>
  <%= @author.main_genre %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @author.birthdate %>
</p>

<p>
  <strong>Info:</strong>
  <%= @author.info %>
</p>

<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: [author, book], local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :book_genre %>
  </div>

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book, author: @author %>

<%= link_to 'Show', [@author, @book] %> |
<%= link_to 'Back', author_books_path(@author) %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.genre %></td>
        <td><%= link_to @author.name, @author %></td>
        <td><%= link_to 'Show', [@author, book] %></td>
        <td><%= link_to 'Edit', edit_author_book_path(@author, book) %></td>
        <td><%= link_to 'Destroy', [@author, book], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_author_book_path(@author) %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book, author: @author %>

<%= link_to 'Back', author_books_path(@author) %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Author:</strong>
  <%= link_to @book.author.name, @book.author %>
</p>

<%= link_to 'Edit', edit_author_book_path(@author, @book) %> |
<%= link_to 'Back', author_books_path(@author) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>